# Generated by Django 5.0.6 on 2024-06-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.TextField(db_column='Student ID', primary_key=True, serialize=False)),
                ('student_name', models.TextField(blank=True, db_column='Student Name', null=True)),
                ('course', models.TextField(blank=True, db_column='Course', null=True)),
                ('year_sem', models.IntegerField(blank=True, db_column='Year/Sem', null=True)),
                ('category', models.TextField(blank=True, db_column='Category', null=True)),
                ('gender', models.TextField(blank=True, db_column='Gender', null=True)),
                ('college_email', models.TextField(blank=True, db_column='College Email', null=True)),
                ('personal_email', models.TextField(blank=True, db_column='Personal Email', null=True)),
                ('student_mobile_number', models.BigIntegerField(blank=True, db_column='Student Mobile Number', null=True)),
                ('admission_criterion', models.TextField(blank=True, db_column='Admission Criterion', null=True)),
                ('cuet_score', models.FloatField(blank=True, db_column='CUET Score', null=True)),
            ],
            options={
                'db_table': '2026_bcom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TallyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('response', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
