# Generated by Django 5.0.6 on 2024-06-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_requesting_delete_tallyresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='requesting',
        ),
    ]
