# Generated by Django 5.0.6 on 2024-07-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_delete_requesting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_expense_id', models.CharField(max_length=255)),
                ('sc_name', models.CharField(max_length=255)),
                ('sc_email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=255)),
                ('company_round', models.CharField(max_length=255)),
                ('bill_number', models.CharField(max_length=255)),
                ('bill_vendor', models.CharField(max_length=255)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
