# Generated by Django 5.0.6 on 2024-07-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_scuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SCUser',
        ),
    ]
