# Generated by Django 5.0.6 on 2024-08-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_delete_scuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
